### ISSUE TITLE
How to branch `cmd bool`?

### ISSUE THREAD

**Issue by RustemB** [byorgey/swarm#119]
how can i do something like this?
```swarm
...
if (ishere "tree") move { grab; turn back; move };
...
```

**Comment by TristanCacqueray** [comment]
You need to bind the `ishere` output using `<-`, e.g. to get the `bool` out of `cmd bool`:

```swarm
istree <- ishere "tree";
if istree move {grab; turn back; move}; 
```

**Comment by byorgey** [comment]
If you have lambdas, you can also define your own version of this pattern, like
```
def ifC : forall a. cmd bool -> cmd a -> cmd a -> cmd a = \test. \then. \else.
  b <- test;
  if b then else
end
```
Then you can just write `ifC (ishere "tree") move { grab; turn back; move }`.

**Comment by RustemB** [comment]
Brent's variant much clear
Thanks

**Comment by byorgey** [comment]
I'll leave this open for the moment since I think we should add it to some kind of FAQ/tips and tricks document, maybe on the wiki?

**Comment by RustemB** [comment]
Maybe add some function like
`forall m0 a0. m0 a0 -> a0`
?

**Comment by byorgey** [comment]
> Maybe add some function like
> `forall m0 a0. m0 a0 -> a0`
> ?

That sure sounds convenient.  Unfortunately, it would be unsafe, for the same reason `unsafePerformIO : IO a -> a` is unsafe in Haskell.  For example (supposing the function is called `run`),  if we had `let thing = run grab in give "base" thing; give "base" thing`, how many times do we execute `grab`?  It could be 1 or 2.  If you think it should be only 1, how about `give "base" (run grab); give "base" (run grab)`?  Surely that will execute `grab` two times.  But those two programs should be the same; the first only gives a name to the common expression `run grab`.  The point is that once we have such a `run : cmd a -> a` function, we no longer have control over when and how many times things get executed.  Or, maybe a better way to say it is, now in order to know when and how many times commands are executed, you must know all the details of how expressions are evaluated at runtime.

**Comment by RustemB** [comment]
then we need something like |case...of expression?

**Comment by byorgey** [comment]
Yes, I guess we will add `case` expressions when we implement #46 .

**Comment by byorgey** [comment]
I've added this to the wiki: https://github.com/byorgey/swarm/wiki/Frequently-Asked-Questions,-Tips-and-Tricks#how-can-i-use-a-cmd-bool-in-an-if
