### ISSUE TITLE
Improved recipe formatting

### ISSUE THREAD

**Issue by mgoadric** [byorgey/swarm#122]
**Is your feature request related to a problem? Please describe.**
It is difficult to easily read the crafting recipes in the info panel, and determine how the item can be used. For example the `log` can be used as an input and an output, but this is not immediately clear from the current recipe display. Additionally, it appears there is a furnace that can be used for crafting, and it is awkward to have it be listed on both the input and output sides.

**Describe the solution you'd like**
A clear and concise format for displaying recipes using ascii graphics, showing the input and count on the left, the crafting space above, and the output items and count on the right, with the item being inspected highlighted, as shown here:

<img width="194" alt="Screen Shot 2021-09-30 at 12 15 11 PM" src="https://user-images.githubusercontent.com/1328659/135501855-5374872c-d64b-4528-89ae-b682fdd91d45.png">

**Comment by byorgey** [comment]
Great ideas, thanks!  Actually a workbench is required for every recipe (even ones that require a furnace), so I propose leaving that out.  But I really like this idea.

I guess an easy first step would be just to highlight the item being inspected, which would already help a bit.

**Comment by byorgey** [comment]
Turns out just highlighting the inspected item as a first step is not actually as easy as I thought, since it would require first doing line wrapping, then finding the name to highlight, then turning it into a `Widget`, but actually it's nontrivial to get our hands on the text after it has been line wrapped but before it has been turned into a widget.

I think this will require something like what we do for the world view: cache the `Extent` when the view is rendered, so that we know how big the panel is and can manually lay out the recipes ourselves using the available width.

**Comment by byorgey** [comment]
@mgoadric It's not finished yet, but would be happy to get any feedback on the above PR so far!

**Comment by byorgey** [comment]
Note I've also been working on #36 which will make the bottom-left panel scrollable.

**Comment by mgoadric** [comment]
Yes, this looks excellent! The word wrapping and furnace appear to be there now as well! Awesome!
