### ISSUE TITLE
Active robot queue

### ISSUE THREAD

**Issue by byorgey** [byorgey/swarm#19]
This is an idea to make the interpreter a bit more efficient, especially if there are lots of "dead" robots lying around.

* In addition to the `robotMap`, add `activeRobots :: [Text]` to the `GameState`, representing the names of robots which are actively running code.
* The `addRobot` function should add a robot to both the `robotMap` and the `activeRobots` list.
* Each tick, we iterate over every robot in `activeRobots` (instead of over every robot in the `robotMap`), filter out any which are inactive, tick the rest, and rebuild the list.

This way we only spend time iterating over the robots which will actually do some computation.

**Comment by twitu** [comment]
There are a few challenges to consider here -

* The order in which the bots are chosen will change. Currently `gameTick` uses `M.keys` which returns the keys in ascending order. However with a list like `activeRobots` the ordering will change depending on when a bot is added to the list.
* This will also be have to be considered once #22 is implemented because previously inactive bots can now become active.
* There'll be a similar challenge with waiting bots #20

**Comment by polux** [comment]
The ordering should stay the same if we make `activeRobots` a `Set`.
