### ISSUE TITLE
Wrap errors shown in game

### ISSUE THREAD

**Issue by xsebek** [byorgey/swarm#241]
I find it annoying when the Error window does not show the full text of the exception.

For example:

![Screenshot from 2021-10-16 17-47-29](https://user-images.githubusercontent.com/44544735/137593894-da9c0f91-bf47-4195-a31f-81e0dc256d60.png)

Here we should wrap the list of commands and make the window larger.

**Comment by byorgey** [comment]
Ah, yeah, that's annoying.

> it could be even nicer if we filtered the list of expected commands to those that are available (in the game mode?), but that is maybe not so easy with the parser.

Megaparsec actually has a lot of stuff for generating custom error messages, so maybe it would actually be possible, I'm not sure.

**Comment by Alexander-Block** [comment]
I think that the problem with wrapping the error message is easily solved. However, I think I do not quite understand this requirement:
 
> it could be even nicer if we filtered the list of expected commands to those that are available (in the game mode?), but that is maybe not so easy with the parser.

@xsebek, could you please elaborate a bit on what you mean by this? I thought that from a purely syntactical point of view all commands should be available in all game modes and that the main difference between game modes is whether there is a check for capabilities. Only listing commands for which base has the required capabilities should be difficult and might not be desirable because the parser does not know anything about capabilities and the static capability checker works on already parsed `Term`s.

If the actual problem is that the error message is too long, it could be a solution to group members of this list as in `expecting ..., built-in command, ...` instead of `expecting ..., "appear", "back", ...`.

**Comment by xsebek** [comment]
Just listing commands should easily fit on two lines and megaparsec can say “or user command” at the end😉 
The filtering comes to mind because of the `appear` command, which is not intended for humans in any game mode as far as I know. Filtering based on inventory would probably be more useful in help. 🤔

**Comment by byorgey** [comment]
> because of the `appear` command, which is not intended for humans in any game mode as far as I know.

I've been working on #15 and we're going to start having more of those commands --- because we will need some sensing commands with God-like omniscience to be able to code the winning conditions for the challenges.

**Comment by Alexander-Block** [comment]
Thank you for the clarification. I really do not see a way to make the parser aware of which commands are available to the user without threading part of the game state through it (since those commands not available to the user -- outside of Creative mode -- are exactly the ones depending on capabilities not provided by any entity). Also, another drawback in listing all commands that are in principle available to the user is that the explorative element of unlocking commands as discussed in #84 can be easily bypassed.  

Because of this together with the fact that even now the list of all commands does not fit into two lines on my display, I think that grouping the user commands is the right way to solve this problem.  I have prepared a pull request for this.
