### ISSUE TITLE
Mechanisms for world exploration & discovery

### ISSUE THREAD

**Issue by amalloy** [byorgey/swarm#49]
It's easy to move the map around, but I couldn't tell what features were interesting or how to interact with them. The tutorial explains trees, which is fine, and I guessed the yellowish C was copper, but to do anything with copper I need a furnace, which needs stone. Where does that come from? I can't point at a tile on the map and ask "is this stone?", and there are multiple grey glyphs which plausibly could be.

**Comment by byorgey** [comment]
Hi, thanks for the feedback, this is super helpful!  Obviously I know what everything is since I programmed it, so it's hard for me to imagine what it's really like playing the game with zero expectations or background knowledge.

On the one hand, I don't want to add a key or allow you to just point at things and ask what they are; part of the conceit of the game is that you can only interact with the world through your robots, so to find out what something is you have to send a robot out to explore it for you. (Then why can you see a top-down view of the world, you ask?  Umm... maybe you left a... satellite in orbit? Or maybe you have some kind of camera mounted on your base? These are definitely questions that need answers...)

However, in any case, the bigger point is well taken: some more careful thought needs to be put into how discoverable things are.  Currently, the only way to find out about an unknown thing would be to (1) send a robot to to `grab` it (2) `view` that robot so you can see its inventory.  However, several aspects of this are unsatisfactory.
* It does not work for things that cannot be `grab`bed.
* If we implement #17 then you won't be able to `view` robots until they have an antenna, which would require you to collect some resources first, creating a sort of Catch-22 situation.
Instead of `view`ing a robot's inventory, you could have the robot `give` things to you --- but in order to `give` an item, you have to know its name!

A few ideas for making this experience better (very open to other suggestions as well):
* Make the `grab` command return the name of the thing that was grabbed.  That way, instead of
    ```
    grab; ... ; give "base" "tree" -- give this thing that I already have to know is called a "tree"
    ```
    you could write
    ```
    thing <- grab; ... ; give "base" thing   -- give whatever the heck it is I just grabbed
    ```
    This seems like a good idea independently of anything else so we should definitely do this: #51
* Give robots some kind of "scanning" ability right off the bat, allowing them to learn the names of things around them.  For example maybe all robots start with a `camera` device which gives them the ability to use a command `scan : dir -> cmd string`.  So you could say `scan forward` to find out the name of the thing in front of you.

**Comment by amalloy** [comment]
One idea I had addresses this in a kinda funny way. Instead of making things more transparent to a new player, make the discovery of glyph meaning a mandatory part of the game by concealing the glyphs until the player explores them (with your camera proposal or whatever). Obviously I don't mean you have to look at every square, that would be miserable. But maybe you look at one tree, and you say, "oh, that's what trees look like on this planet", and now the glyph for trees becomes a green T.

This feels sorta like the scroll/potion ID minigame in roguelikes, and seems sorta defensible flavor-wise: you don't know what these strange alien objects are until you explore them. Does this direction seem interesting to you?

**Comment by byorgey** [comment]
Hmm, that's an interesting idea!  I am a bit torn, on the one hand I think it does fit very nicely flavor-wise.  On the other hand, on purely aesthetic grounds I want it to look pretty when people first start up the game! =)  Ah, but maybe I just answered my own objection: perhaps before you have identified an item, it shows up as a question mark, but uses the color of the item (even if you don't know what something is, you can still see what color it is).

**Comment by byorgey** [comment]
That doesn't look bad at all:

![unknowns](https://user-images.githubusercontent.com/533859/134738836-ccd70d31-9b72-4011-af22-0b0692596c75.png)

(The things in your inventory shouldn't be displayed with question marks, but I just did a quick-and-dirty edit to the entity display code just to get a sense for what it would look like.)

I think I like this idea!  It doesn't directly address the problem of making things more discoverable, but it makes it more explicit that you are supposed to send robots to discover things for you.

**Comment by Anrock** [comment]
> I don't want to add a key or allow you to just point at things and ask what they are

I get the idea behind this, but still would be nice to have either point ability or at least a map legend with already known entities.

> (scan command) There is still the problem of how to get this information from a robot back to the base

Same as "give" but for scanner data maybe? Like `{ move east; scanned_thing <- scan forward; turn back; move; upload "base" scanned_thing }`. Logger thingie won't cut it, imo - I, as a player, will have a textual description of a thing, but the game won't know that I know what that thing is and it won't be added to legend, yadda-yadds. And specifically me, as a player with bad memory, will have to write down the description somewhere in order to remember what was that "red V thingie" :D

**Comment by byorgey** [comment]
> Same as "give" but for scanner data maybe? Like `{ move east; scanned_thing <- scan forward; turn back; move; upload "base" scanned_thing }`

Ah, nice idea!  Maybe then the thing would show up in your inventory but with a count of zero, so you could still read about it even though you don't have one.  Right now I don't think you can add zero of something to an inventory, but that would be a very easy change.

> How about a fog of war? Everything is hidden by default when world is generated and you only see a base tile but base has a camera device.

Oh, that's a nice idea too!  Shouldn't be too hard to implement either --- just keep a set of tile IDs that you can see, and have that affect how the world renders.

This issue seems to have shifted emphasis over time, so I've changed the name (open to better suggestions though).  Also, perhaps we should start splitting out some of the ideas generated here into separate issues.

**Comment by Anrock** [comment]
> the thing would show up in your inventory but with a count of zero

If the map legend on help screen going to be implemented you can put "scan data of <thing>" or something like that into inventory with a count of 1 to workaround the 0 count quirk.

> perhaps we should start splitting out some of the ideas generated here into separate issues.

Agree. Seems like fog of war and camera can be already separated.

**Comment by byorgey** [comment]
I split out an issue to create a `scanner` device in #96.

On further reflection re: fog of war, I am no longer so convinced it is a good idea, primarily because I think it would actually add quite a bit of complexity to do it right.  If we're going to say that the base can only see a certain area around it, and farther areas must be viewed by robots and then uploaded to the base, it doesn't make sense that the base can then magically see those areas or tiles *as they are now*.  It should see a *snapshot* of the way they were when the robot viewed it, but not any further updates.  That sounds rather complex though: now we have to track not only tiles corresponding to the current state of the world, but also some different tiles corresponding to the base's knowledge of what the world used to look like...

I can think of two other directions to go.  One would be to say that instead of *crash-landing* on a planet, you have been *sent to explore* a planet.  So you do indeed have a a fleet of support satellites in orbit, which can send you real-time images of the planet's surface.   If that's the story, it would imply that you can indeed scroll around the world map at will.

In contrast, #32 suggests simply disabling world scrolling.  The story here would be that you have a camera on your base that can see a limited distance around it (perhaps just however big your terminal happens to be), and if you want to see other regions you have to send a robot with a camera which can broadcast its view back to you via the `view` command.

**Comment by Anrock** [comment]
@GnarLito this will grow memory consumption and save size indefinitely. Bad idea, IMO.

@byorgey 
>It should see a snapshot of the way they were when the robot viewed it, but not any further updates

What kind of updates may happen? World is pretty static as of now. Even if enemy\neutral entities are introduced - instead of snapshots game should render just landscape without dynamic entities and that's it, no? And landscape doesn't change.

**Comment by byorgey** [comment]
> World is pretty static as of now.

Not really. Since robots can `grab` and `place` things, the landscape can change quite a bit.

**Comment by twitu** [comment]
One possible addition to this line of thought.

Maybe in the inventory section under `Installed devices` add a section called "Found tiles" or `Discovered entities". This shows the mapping between a discovered type of entity and it's character. For example 'T' -> "Tree", or 'C' -> "Copper".

This makes it possible for the player to -
* see their progress at a glance
* to quickly look up some letter they might have forgotten

I feel this still keeps in line with the original thought that the world should be explored and interacted by the robots. But this does make it a bit easier for the players, especially when they're starting to play the game.

**Comment by byorgey** [comment]
How about this: once an entity goes into your inventory, it is always there (but possibly with a 0)?  And maybe there is also a key to toggle whether to show all entities you have discovered, or only the ones you have at least one of right now.  This fits well with #96.

**Comment by xsebek** [comment]
This would be a fantastic change! :+1: the 0 entities would have to propagate during the build - it will be funny to view some ol' robot and see only `?` everywhere, but I guess that is what `upload` is for :laughing:

**Comment by byorgey** [comment]
> the 0 entities would have to propagate during the build

Hmm, but given the existence of `upload`, couldn't we just let users deal with this manually?  For most robots I build I don't actually care if they know what everything is, I just want them to follow my instructions.  In the case that I do care (say, because I am planning to `view` it), I could just manually `upload` to it before sending it off.  What do you think?

**Comment by xsebek** [comment]
I think it's an ingenious plan to make players search the wiki FAQ for `upload` tips :smiling_imp: 

Jokes aside, I am fine without propagation. :slightly_smiling_face:  It would keep the code slightly more straightforward, consume somewhat less memory and as long as `upload` has a reasonable range, not bother anyone at all.

**Comment by xsebek** [comment]
@amalloy @byorgey I propose to close this by implementing entity hiding with `?` in #276, unless there are ideas here that we also want to implement? :slightly_smiling_face:

Some of the other ideas here have already split off into separate issues:
- scanner: #96 
- antenna: #17 
- fog of war: replaced by no scrolling
- no scrolling: #32
- the toggle key for hiding 0 in inventory: *no issue yet*

**Comment by byorgey** [comment]
Sounds good to me.  We should definitely make an issue for a key to toggle showing known things with 0 copies in the inventory.
