### ISSUE TITLE
Tree at base?

### ISSUE THREAD

**Issue by gilgamec** [byorgey/swarm#90]
**Describe the bug**

I'm not sure if this is intended or not, but upon starting in a new world, `grab` issued at the base will grab a `"tree"`, adding a tree to the base's inventory. The map does not appear to change. Eventually the base tree will regrow and can be `grab`bed again.

**To Reproduce**

Start the game. Enter `grab` at the REPL.

Or just ask `ishere "tree"`.

**Expected behavior**

Either there's no tree at base, or the map shows it ... or maybe it's just an Easter egg.

**Comment by byorgey** [comment]
Hi `gilgamec`, thanks for the report!  This is actually not a bug --- I guess you could consider it an easter egg of sorts.  When the world is generated, we want to make sure the base is near a forest, since many of the devices needed for the early game depend on getting some trees.  So we search for a cell containing a tree and shift the world so that cell becomes the new origin.  You can see this happening here:

https://github.com/byorgey/swarm/blob/main/src/Swarm/Game/WorldGen.hs#L107

The reason the map does not change when the base executes `grab` is that robots (including the base) are always drawn on top of any entities in the same cell.  So the base is blocking your view of the tree.

(Incidentally, the reason the base has a grabber at all is because I wanted it to be able to `give` things to other robots.)

It is kind of a funny coincidence that using seed 0 (which is the only world you can play at the moment), there happens to be a single isolated tree a few steps away from a bigger forest, and that is the tree that is found.  Presumably in most other worlds generated from other seeds the base will end up right on the edge of a forest (but still on top of a tree).

**Comment by byorgey** [comment]
I was going to add that we could e.g. change the world generation so that it finds a location for the base which is *near*, but not *on top of*, a tree.  I would certainly be open to that if people would prefer it.

**Comment by xsebek** [comment]
In #170 I implemented the suggested neighbour check. It slightly changes `TUTORIAL.md`, but luckily none of the commands there interacts with the base tree.

When we do a more significant change, the images and commands could be modified to use the tree that is one step away. :thinking:
